version: '3.3'
services:
  citizen:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - citizen_db
      - redis

  citizen_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/citizen
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/citizen
  redis:
    image: "redis"
    ports:
      - 6380:6380
  celery:
    build: .
    command: celery -A app worker -l info
    volumes:
      - .:/app
    depends_on:
      - citizen_db
      - redis
  celery-beat:
    build: .
    command: celery -A app beat -l info
    volumes:
      - .:/app
    depends_on:
      - citizen_db
      - redis
     